# Generated by Django 5.2.14 on 2026-05-07 10:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_name', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('PAYU', 'PayU'), ('UPI', 'UPI')], max_length=20)),
                ('internal_status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING_GATEWAY', 'Pending Gateway'), ('PROCESSING', 'Processing'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('PARTIALLY_CAPTURED', 'Partially Captured'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('DISPUTED', 'Disputed'), ('EXPIRED', 'Expired')], max_length=20)),
                ('gateway_status', models.CharField(max_length=100)),
                ('reconciled', models.BooleanField(db_index=True, default=False)),
                ('discrepancy', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_name', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('PAYU', 'PayU'), ('UPI', 'UPI')], db_index=True, max_length=20)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('gateway_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_payload', models.JSONField()),
                ('normalized_payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('DUPLICATE', 'Duplicate'), ('IGNORED', 'Ignored')], db_index=True, default='RECEIVED', max_length=20)),
                ('signature_valid', models.BooleanField(blank=True, null=True)),
                ('deduplication_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment')),
            ],
        ),
    ]
