# Generated by Django 5.2.14 on 2026-05-13 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_refund_payment_remove_paymentattempt_payment_and_more'),
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookevent',
            name='payment',
        ),
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('payload_hash', models.CharField(max_length=64)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('signature', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DLQ', 'Dead Letter Queue')], default='PENDING', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('status__in', ['PENDING', 'FAILED'])), fields=['next_retry_at'], name='idx_webhook_queue_pending')],
            },
        ),
        migrations.DeleteModel(
            name='ReconciliationRecord',
        ),
        migrations.DeleteModel(
            name='WebhookEvent',
        ),
        migrations.AddConstraint(
            model_name='processedwebhookevent',
            constraint=models.UniqueConstraint(fields=('gateway', 'event_id'), name='unique_gateway_event'),
        ),
    ]
