# Generated by Django 5.2.14 on 2026-05-07 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_name', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('PAYU', 'PayU'), ('UPI', 'UPI')], max_length=20, unique=True)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('UNHEALTHY', 'Unhealthy'), ('CIRCUIT_OPEN', 'Circuit Open')], default='HEALTHY', max_length=20)),
                ('success_rate', models.FloatField(default=1.0)),
                ('avg_latency_ms', models.FloatField(default=0.0)),
                ('p95_latency_ms', models.FloatField(default=0.0)),
                ('error_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('circuit_open_at', models.DateTimeField(blank=True, null=True)),
                ('circuit_reset_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GatewayHealthLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_name', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('PAYU', 'PayU'), ('UPI', 'UPI')], max_length=20)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('UNHEALTHY', 'Unhealthy'), ('CIRCUIT_OPEN', 'Circuit Open')], max_length=20)),
                ('success_rate', models.FloatField()),
                ('avg_latency_ms', models.FloatField()),
                ('error_count', models.IntegerField()),
                ('total_count', models.IntegerField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('strategy', models.CharField(choices=[('WEIGHTED', 'Weighted'), ('ROUND_ROBIN', 'Round Robin'), ('PRIORITY', 'Priority'), ('COST_OPTIMIZED', 'Cost Optimized'), ('FAILOVER_ONLY', 'Failover Only')], max_length=20)),
                ('priority', models.IntegerField(default=100)),
                ('conditions', models.JSONField()),
                ('gateway_weights', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
