# Generated by Django 5.2.14 on 2026-05-13 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitBreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=50)),
                ('payment_method', models.CharField(default='ALL', max_length=50)),
                ('state', models.CharField(choices=[('CLOSED', 'Closed'), ('OPEN', 'Open'), ('HALF_OPEN', 'Half-Open')], default='CLOSED', max_length=20)),
                ('failure_count', models.IntegerField(default=0)),
                ('failure_threshold', models.IntegerField(default=5)),
                ('recovery_timeout_seconds', models.IntegerField(default=30)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('gateway', 'payment_method')},
            },
        ),
        migrations.CreateModel(
            name='GatewayConfig',
            fields=[
                ('gateway_name', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('PAYU', 'PayU'), ('UPI', 'UPI')], max_length=50, primary_key=True, serialize=False)),
                ('connection_details', models.JSONField()),
                ('feature_flags', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GatewayHealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(db_index=True, max_length=50)),
                ('success_rate', models.FloatField()),
                ('p95_latency_ms', models.IntegerField()),
                ('error_rate', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='GatewayRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('selection_reason', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('discrepancy_type', models.CharField(max_length=100)),
                ('internal_state', models.CharField(max_length=50)),
                ('gateway_state', models.CharField(max_length=50)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutingConfig',
            fields=[
                ('config_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GatewayHealth',
        ),
        migrations.DeleteModel(
            name='GatewayHealthLog',
        ),
        migrations.DeleteModel(
            name='RoutingRule',
        ),
        migrations.AddIndex(
            model_name='gatewayhealthmetrics',
            index=models.Index(fields=['gateway', 'recorded_at'], name='orchestrato_gateway_9d1ba6_idx'),
        ),
    ]
