# Generated by Django 5.2.14 on 2026-05-13 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_circuitbreaker_gatewayconfig_gatewayhealthmetrics_and_more'),
        ('payments', '0002_remove_refund_payment_remove_paymentattempt_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayroute',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_attempts', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='reconciliationlog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.transaction'),
        ),
    ]
