# Generated by Django 5.2.14 on 2026-05-13 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentattempt',
            name='payment',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='status',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='refund',
            name='gateway_refund_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_order_id', models.CharField(db_index=True, max_length=255)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('state', models.CharField(choices=[('CREATED', 'Created'), ('ROUTE_SELECTED', 'Route Selected'), ('AUTH_INITIATED', 'Auth Initiated'), ('AUTHORISED', 'Authorised'), ('AUTH_FAILED', 'Auth Failed'), ('CAPTURE_INITIATED', 'Capture Initiated'), ('CAPTURED', 'Captured'), ('PARTIALLY_CAPTURED', 'Partially Captured'), ('CAPTURE_FAILED', 'Capture Failed'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], db_index=True, default='CREATED', max_length=20)),
                ('gateway_name', models.CharField(blank=True, choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('PAYU', 'PayU'), ('UPI', 'UPI')], db_index=True, max_length=20, null=True)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['gateway_name', 'state'], name='payments_tr_gateway_537788_idx')],
            },
        ),
        migrations.CreateModel(
            name='GatewayRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_name', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('PAYU', 'PayU'), ('UPI', 'UPI')], db_index=True, max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(choices=[('CREATED', 'Created'), ('ROUTE_SELECTED', 'Route Selected'), ('AUTH_INITIATED', 'Auth Initiated'), ('AUTHORISED', 'Authorised'), ('AUTH_FAILED', 'Auth Failed'), ('CAPTURE_INITIATED', 'Capture Initiated'), ('CAPTURED', 'Captured'), ('PARTIALLY_CAPTURED', 'Partially Captured'), ('CAPTURE_FAILED', 'Capture Failed'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], max_length=20)),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('is_failover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='refund',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.transaction'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TransactionStateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(choices=[('CREATED', 'Created'), ('ROUTE_SELECTED', 'Route Selected'), ('AUTH_INITIATED', 'Auth Initiated'), ('AUTHORISED', 'Authorised'), ('AUTH_FAILED', 'Auth Failed'), ('CAPTURE_INITIATED', 'Capture Initiated'), ('CAPTURED', 'Captured'), ('PARTIALLY_CAPTURED', 'Partially Captured'), ('CAPTURE_FAILED', 'Capture Failed'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], max_length=20)),
                ('to_state', models.CharField(choices=[('CREATED', 'Created'), ('ROUTE_SELECTED', 'Route Selected'), ('AUTH_INITIATED', 'Auth Initiated'), ('AUTHORISED', 'Authorised'), ('AUTH_FAILED', 'Auth Failed'), ('CAPTURE_INITIATED', 'Capture Initiated'), ('CAPTURED', 'Captured'), ('PARTIALLY_CAPTURED', 'Partially Captured'), ('CAPTURE_FAILED', 'Capture Failed'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], max_length=20)),
                ('event', models.CharField(max_length=100)),
                ('gateway_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(max_length=100)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='payments.transaction')),
            ],
        ),
        migrations.DeleteModel(
            name='StateTransition',
        ),
    ]
