# Generated by Django 5.2.14 on 2026-05-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_refund_payment_remove_paymentattempt_payment_and_more'),
        ('webhooks', '0002_remove_webhookevent_payment_processedwebhookevent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentAttempt',
        ),
    ]
