# Generated by Django 5.2.14 on 2026-05-15 06:18

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_delete_payment_delete_paymentattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewayroute',
            name='state',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ROUTE_SELECTED', 'Route Selected'), ('ROUTE_FAILED', 'Route Failed'), ('AUTH_INITIATED', 'Auth Initiated'), ('AUTHORISED', 'Authorised'), ('AUTH_FAILED', 'Auth Failed'), ('CAPTURE_INITIATED', 'Capture Initiated'), ('CAPTURED', 'Captured'), ('PARTIALLY_CAPTURED', 'Partially Captured'), ('CAPTURE_FAILED', 'Capture Failed'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default=apps.core.utils.generate_16_char_id, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ROUTE_SELECTED', 'Route Selected'), ('ROUTE_FAILED', 'Route Failed'), ('AUTH_INITIATED', 'Auth Initiated'), ('AUTHORISED', 'Authorised'), ('AUTH_FAILED', 'Auth Failed'), ('CAPTURE_INITIATED', 'Capture Initiated'), ('CAPTURED', 'Captured'), ('PARTIALLY_CAPTURED', 'Partially Captured'), ('CAPTURE_FAILED', 'Capture Failed'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], db_index=True, default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionstatelog',
            name='from_state',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ROUTE_SELECTED', 'Route Selected'), ('ROUTE_FAILED', 'Route Failed'), ('AUTH_INITIATED', 'Auth Initiated'), ('AUTHORISED', 'Authorised'), ('AUTH_FAILED', 'Auth Failed'), ('CAPTURE_INITIATED', 'Capture Initiated'), ('CAPTURED', 'Captured'), ('PARTIALLY_CAPTURED', 'Partially Captured'), ('CAPTURE_FAILED', 'Capture Failed'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionstatelog',
            name='to_state',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ROUTE_SELECTED', 'Route Selected'), ('ROUTE_FAILED', 'Route Failed'), ('AUTH_INITIATED', 'Auth Initiated'), ('AUTHORISED', 'Authorised'), ('AUTH_FAILED', 'Auth Failed'), ('CAPTURE_INITIATED', 'Capture Initiated'), ('CAPTURED', 'Captured'), ('PARTIALLY_CAPTURED', 'Partially Captured'), ('CAPTURE_FAILED', 'Capture Failed'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], max_length=20),
        ),
    ]
