# Generated by Django 5.2.14 on 2026-05-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idempotency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IdempotencyRecord',
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(condition=models.Q(('status', 'COMPLETED'), _negated=True), fields=['expires_at'], name='idx_idempotency_expires'),
        ),
    ]
